sudo: required
services:
  - docker

before_install:
  - docker build -t sohil2609/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sohil2609/docker-react npm run test -- --coverage
